# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["SKIP_BUNDLING"] = "1"
    sh("pnpm --dir .. install --frozen-lockfile")
    sh("pnpm --dir .. run podInstall")
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "development"
	lane :build_dev do |options|
		sh("pnpm --dir .. run bundle:ios")
		update_info_plist
		update_code_signing_settings
		increment_version_number
		build_app(
			scheme: "taroDemo",
			workspace: "taroDemo.xcworkspace",
			export_method: "development",
			configuration: "Debug",
			clean: true,
			xcargs: "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) DEBUG=1'",
			export_options: {
				method: "development",
				compileBitcode: false
			}
		)
	end

	desc "release"
	lane :build_release do |options|
		UI.user_error!(
			"iOS release is disabled until signing, Gemfile.lock and Podfile.lock are configured on macOS."
		)
	end
	
end
