export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/login/index',
    'pages/express/index',
    'pages/express/success/index',
    'pages/express/insurance/index',
    'pages/query/price/index',
    'pages/query/dispatch/index',
    'pages/query/stations/index',
    'pages/query/stations/detail/index',
    'pages/query/goods/index',
    'pages/account/settings/index',
    'pages/account/cancel/index',
    'pages/realname/center/index',
    'pages/contact/list/index',
    'pages/contact/edit/index',
    'pages/order/list/index',
    'pages/order/detail/index',
    'pages/order/cancel/index',
    'pages/order/stub/index',
    'pages/payment/list/index',
    'pages/coupon/list/index',
    'pages/coupon/detail/index',
    'pages/support/center/index',
    'pages/customer/center/index',
    'pages/sign/code/index',
    'pages/ecard/center/index',
    'pages/member/index/index',
    'pages/invoice/index/index',
    'pages/invoice/apply/index',
    'pages/invoice/detail/index',
    'pages/invoice/preview/index',
    'pages/invoice/taxpayer/index',
    'pages/invoice/taxpayer/edit/index',
    'pages/privacy/settings/index',
    'pages/mine/index',
    'pages/web/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '德邦快递',
    navigationBarTextStyle: 'black'
  }
})
